version: '2'

networks:
  app-tier:
    driver: bridge

services:
  redis:
    image: 'samarben/y.github.io:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier
  myapp:
    image: 'YOUR_APPLICATION_IMAGE'
    networks:
      - app-tier
