version: '2'
services:
  guides:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bundle exec middleman
    ports:
      - "4567:4567"
    volumes:
      - .:/src
    
    redis:
    restart: always
    image: redis:5-alpine
    ports:
      - '6379:6379'

app:
    build:
      context: app
      dockerfile: Dockerfile
