version: "3"  # optional since v1.27.0
   services:
  web:
    image: {{name}}:latest
    build:
      context: .
    environment:
      <<: *shared_environment{{#fluent}}{{^db.is_sqlite}}
    depends_on:
      - db{{/db.is_sqlite}}{{/fluent}}
    ports:
      - '8080:8080'
    volumes:
      - .:/code
      - logvolume01:/var/log
    links:
      - redis
  redis:
    image: redis
volumes:
  logvolume01: {}
